title: Earth-Star Sustainable Abundance
description: A scalable urban ecosystem for sustainability and AI leadership
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
baseurl: "/EarthStarSmartCity"
url: "https://drcarver.github.io"
